In [3]:
import pandas as pd
import numpy as np

In [4]:
# input data
Drinks = pd.read_csv('/content/drive/MyDrive/Machine Learning/drinks.csv')

# Menampilkan data
Drinks.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0      Asia  
1                           4.9    Europe  
2                           0.7    Africa  
3                          12.4    Europe  
4                           5.9    Africa

In [5]:
# menampilkan informasi data
Drinks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   country                       193 non-null    object 
 1   beer_servings                 193 non-null    int64  
 2   spirit_servings               193 non-null    int64  
 3   wine_servings                 193 non-null    int64  
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     193 non-null    object 
dtypes: float64(1), int64(3), object(2)
memory usage: 9.2+ KB


In [6]:
# Mengecek apakah ada deret yang kosong
Drinks.empty

False

In [7]:
# Melihat ukuran dari data
Drinks.size

1158

In [19]:
# Variabel independen
x = Drinks.drop(["spirit_servings","country","continent"], axis = 1)
x.head()

beer_servings  wine_servings  total_litres_of_pure_alcohol
0              0              0                           0.0
1             89             54                           4.9
2             25             14                           0.7
3            245            312                          12.4
4            217             45                           5.9

In [20]:
# Variabel dependen
y = Drinks["spirit_servings"]
y.head()

0      0
1    132
2      0
3    138
4     57
Name: spirit_servings, dtype: int64

In [21]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [22]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive bayes
modelnb = GaussianNB()

# Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([17.,  7.,  6.,  8.,  3.,  1.,  3.,  1.,  2.,  1.,  1.,  2.,  2.,
        3.,  1.,  1.,  1.,  1.,  1.,  1.,  3.,  1.,  1.,  2.,  2.,  1.,
        1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  3.,  2.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  2.,  1.,  4.,  1.,  2.,  1.,  2.,  2.,  2.,
        2.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.])

In [23]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([ 16, 114,   1,   1,  41,   0,   1, 117, 133,   1,   3, 326, 173,
       117, 326, 215,  15,   1, 173,  35,  18, 133,  18,   1, 133,   2,
         1,   4,   3,   1, 100,   1,   3, 133,   0,  15,  11,  63,  63])

In [24]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[2.91891249e-03, 4.71544670e-06, 2.41231866e-01, ...,
        2.31881761e-02, 0.00000000e+00, 0.00000000e+00],
       [1.52135617e-09, 8.34806087e-44, 2.90871735e-12, ...,
        1.38828673e-01, 0.00000000e+00, 0.00000000e+00],
       [5.15937698e-02, 3.77931252e-01, 3.54740919e-02, ...,
        9.44966520e-06, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.24612634e-03, 2.32878868e-02, 3.31998227e-03, ...,
        1.94967181e-06, 0.00000000e+00, 0.00000000e+00],
       [5.02216668e-13, 3.52013455e-24, 3.82726008e-07, ...,
        8.03468076e-02, 0.00000000e+00, 0.00000000e+00],
       [9.38010851e-02, 1.26698961e-08, 4.91318539e-02, ...,
        1.55273413e-02, 0.00000000e+00, 0.00000000e+00]])

In [25]:
# import confusion_matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[0, 5, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         6
           1       0.11      0.50      0.18         2
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         0
          18       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         2
          25       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         1
          31       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          41       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1